### ISSUE TITLE
Sub-titular content on github has bad char

### ISSUE THREAD

**Issue by shalecraig** [mouse-reeve/mastodon#17]
[Issue text goes here].
![screen shot 2017-04-13 at 6 24 43 pm](https://cloud.githubusercontent.com/assets/679197/25026828/7cefbe14-2076-11e7-8ed1-4650056ace21.jpg)

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by bitspill** [comment]
`A GNU Social-congruous microblogging facilitator: the oulipo fork`

Edit: `harmonious` might work better than `congruous`

**Comment by mouse-reeve** [comment]
fixt
