### ISSUE TITLE
Local indicator 🇪moji will pass validation in toot body

### ISSUE THREAD

**Issue by etjossem** [mouse-reeve/mastodon#25]
http://emojipedia.org/regional-indicator-symbol-letter-e/

![image](https://cloud.githubusercontent.com/assets/1661633/25055156/078576fa-2116-11e7-8608-1e76cbd6fd11.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mouse-reeve** [comment]
Duplication of https://github.com/mouse-reeve/mastodon/issues/10

**Comment by mlc** [comment]
this is a bit tricky: whilst Oulipo ought to forbid a local indicator symbol in isolation, it's blurry for dual-char glyphs such as a flag for Spain.

to wit: if you forbid this symbol, and a toot contains a Spanish flag and an Irish flag, a wrong program might output a star, a flag for a country known to ISO3166 as [SI](https://en.wiktionary.org/wiki/SI#Translingual), and again a star!
