### ISSUE TITLE
Backward glyph avoids validation in "Display alias"

### ISSUE THREAD

**Issue by etjossem** [mouse-reeve/mastodon#26]
Backward glyph (Ǝ) rightly has validation in toot body but avoids validation in "display alias."

![image](https://cloud.githubusercontent.com/assets/1661633/25055076/98e92a66-2115-11e7-8b71-4d8bc80299c7.png)

Mayhaps additional diacritic variants (é, ė?) pass "display alias" validation.

https://en.wikipedia.org/wiki/%C6%8E

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mouse-reeve** [comment]
duplication of https://github.com/mouse-reeve/mastodon/issues/10
