### ISSUE TITLE
Paragraph margins too big

### ISSUE THREAD

**Issue by mbrubeck** [mouse-reeve/mastodon#28]
It's as if any CR/LF in a toot turns into two, giving paragraphs surplus margins.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mouse-reeve** [comment]
truly! I'm hoping if I bring us up with Mastodon main branch that'll fix this.

**Comment by mouse-reeve** [comment]
fixt!
