### ISSUE TITLE
'moji suffix for skin color contains fifth glyph

### ISSUE THREAD

**Issue by danielbolan** [mouse-reeve/mastodon#29]
As it stands I can't post any 'moji without a mustard tint... :-1: It looks as though `emojione` is making this complication, though a shim in `emoji.jsx` may work to fix this. I may try this tomorrow, should my day allow it.

Also, I would :heart: any thoughts on how to say 'moji idiomatically.

* * * *

 - [x] I took a look at historical bugs to find out if this is a duplication or not.

**Comment by mouse-reeve** [comment]
I can add a rgxp to allow any icons - a workaround for now is to copy in an icon and not using Mastodon's built in tool for it

**Comment by mouse-reeve** [comment]
Fix is waiting for deployment 👍

**Comment by mouse-reeve** [comment]
try it now!
