### ISSUE TITLE
Show fifth symbol brought in from non-oulipo Mastodons as a *

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/mastodon#3]
Is this a good plan?

**Comment by mouse-reeve** [comment]
Snag: ruins urls and html

**Comment by vielmetti** [comment]
URL ruining fix: tinyurl?

**Comment by vielmetti** [comment]
Or omit glyphs, or a standard invalid symbol glyph?

**Comment by mouse-reeve** [comment]
I think tinyurl/bitly isn't a good plan - it would jank up Mastodon's basic functionality too much

**Comment by mouse-reeve** [comment]
I think putting * on top of taboo symbols will work and is a good solution, but I'm too busy to do it right now.

**Comment by mouse-reeve** [comment]
Awaiting pushout

**Comment by mouse-reeve** [comment]
Finally, fixt!
