### ISSUE TITLE
can't put that glyph in the find box

### ISSUE THREAD

**Issue by moonmilk** [mouse-reeve/mastodon#33]
Normally nobody wants to look for that glyph, but way i was told to boost or talk back to a toot on an away instantiation was to copy and stick its URL into that find box. Outmastodon URLs may contain that glyph. (As may ours?)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mouse-reeve** [comment]
Oh thank you, I forgot to fix this

**Comment by mouse-reeve** [comment]
This is up
