### ISSUE TITLE
About contains that fifth symbol

### ISSUE THREAD

**Issue by Ranlvor** [mouse-reeve/mastodon#36]
The Social Contract paragraph of [about](https://oulipo.social/about/more) contains that fifth symbol in its first listing. You should use roman counting not latin symbols.

* * * *

- [x] I sarchd or browsd the rpo’s other issus to nsure this is not a duplicat.

**Comment by mouse-reeve** [comment]
I should fix this but also it's so funny?

**Comment by Ranlvor** [comment]
Noticing it was funny a lot.
