### ISSUE TITLE
Validation fail notification, in a fit of irony, contains fifth symbol

### ISSUE THREAD

**Issue by etjossem** [mouse-reeve/mastodon#38]
Should flash "validation did not pass: status has an invalid symbol", or show visitor a notification of vast wit.

![image](https://cloud.githubusercontent.com/assets/1661633/25248137/fae6caec-25c1-11e7-82be-37499a4116ed.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mouse-reeve** [comment]
oh no! thanks for pointing that out

**Comment by mouse-reeve** [comment]
fix is live
